version: '3.8'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: datus-hive-namenode
    environment:
      - CLUSTER_NAME=datus-hive
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9870:9870"
    volumes:
      - namenode_data:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datus-hive-datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    ports:
      - "9864:9864"
    volumes:
      - datanode_data:/hadoop/dfs/data
    depends_on:
      - namenode

  metastore-db:
    image: postgres:13
    container_name: datus-hive-metastore-db
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5434:5432"
    volumes:
      - metastore_db:/var/lib/postgresql/data

  hive-metastore:
    image: bde2020/hive-metastore:2.3.2-postgresql-metastore
    container_name: datus-hive-metastore
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://metastore-db:5432/metastore
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionUserName=hive
      - HIVE_CORE_CONF_javax_jdo_option_ConnectionPassword=hive
      - HIVE_SITE_CONF_hive_metastore_uris=thrift://hive-metastore:9083
    ports:
      - "9083:9083"
    depends_on:
      - namenode
      - datanode
      - metastore-db

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: datus-hive-server2
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HIVE_SITE_CONF_hive_metastore_uris=thrift://hive-metastore:9083
      - HIVE_SITE_CONF_hive_server2_thrift_port=10000
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore

volumes:
  namenode_data:
  datanode_data:
  metastore_db:
